name: Test

on: workflow_dispatch

jobs:
    integration:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: Use Java Version ${{ matrix.java }}
                uses: actions/setup-java@v1
                with:
                    java-version: ${{ matrix.java }}

            -   name: Install
                run: gradle dependencies

            -   name: Test
                run: gradle integrationTest
                env:
                    mnemonic: ${{ secrets.MNEMONIC }}
