name: Test

on: workflow_dispatch

jobs:
    integration:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            -   name: Use Java Version 8
                uses: actions/setup-java@v1
                with:
                    java-version: 8

            -   name: Install
                run: gradle dependencies

            -   name: Test
                run: gradle integrationTest
                env:
                    INTEGRATION_TESTS_MNEMONIC: ${{ secrets.MNEMONIC }}
